### PR TITLE
Master tool

### PR DESCRIPTION
**Pull request by ruhan1**
This is a CLI tool to list/delete paths from pathDB. Usage:
 -d,--delete <arg>       delete specified file
 -f,--filesystem <arg>   filesystem
 -h,--host <arg>         host (default localhost)
 -i,--info <arg>         get specified path info
 -k,--keyspace <arg>     keyspace
 -l,--list <arg>         list specified path
 -p,--port <arg>         port (default 9042)
 -P,--pass <arg>         password
 -t,--type <arg>         filter list result by type (file/dir)
 -u,--user <arg>         username

Example, -k promotealltest -f maven:hosted:source -l /first and it will print something like this:
$ ls -l /first -t all
/first
/first/data
/first/data/d1.txt
/first/path.http-metadata.json

But...you can only run it with a Cassandra session (i.e., run on a nearby pod). I think this is necessary to add a few REST endpoints in Indy to provider similar operations.

### CODE REVIEW

**Comment by ligangty** [comment]
I suggest to use a separate module to include this because it will bring extra deps to the main function(like commons-cli). It will increase the final indy package which includes the deps that indy does not need.

**Comment by ruhan1** [comment]
Fair enough. I add a module named "tool".

**Comment by ruhan1** [comment]
Oh... This does not compile. I need to add the current artifact to a module too.

**Comment by ruhan1** [comment]
I think we also need to separate the JPA and Cassandra impls to remove dependencies on rdbms things. I will do it later.

**Comment by ruhan1** [comment]
Okay, the modules are good now. Pls review again. @ligangty

**Comment by ligangty** [comment]
Sounds good. We should always think to minimize the final package size.

**Review by ligangty — APPROVED** [review]

**Pull request merged**
