### PR TITLE
Restore write consistent level to QUORUM

### PR DESCRIPTION
**Pull request by ruhan1**
To fix: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
We have been too aggresive in terms of writing.

### CODE REVIEW

**Comment by sswguo** [comment]
Do we need to consider the write consistence level and read one together, if we want "strong consistence", do we need to keep: W(write)+R(read)>RF(replica factor)?

I googled several article about this, that recommends: 
WRITE CL=QUORUM, READ CL=QUORUM: it will give high read and write speed without sacrificing availability.
https://dzone.com/articles/tuning-consistency-with-apache-cassandra

**Comment by ruhan1** [comment]
@sswguo yes. this pr is to restore pathmap's w to quorum. r is quorum too.

**Comment by sswguo** [comment]
> @sswguo yes. this pr is to restore pathmap's w to quorum. r is quorum too.

See, LGTM. :)

**Comment by ruhan1** [comment]
@sswguo this fix might not enough. the other part of the fix is in indy - retrypolicy. we have a read retry policy, nothing for write. I will push another pr later. I hope the two fixes can fix the problem. if still happens, then we have to dig into cassandra to find why.

**Comment by sswguo** [comment]
> @sswguo this fix might not enough. the other part of the fix is in indy - retrypolicy. we have a read retry policy, nothing for write. I will push another pr later. I hope the two fixes can fix the problem. if still happens, then we have to dig into cassandra to find why.

Sure, thanks for the info.

**Comment by sswguo** [comment]
Another thing, there are some timeout options in cassandra.yaml in server-side, let's see if we need to tune them when the timeout thing still happens after above fixes.
`
read_request_timeout_in_ms: 5000  
range_request_timeout_in_ms: 10000  
write_request_timeout_in_ms: 2000  
counter_write_request_timeout_in_ms: 5000  
cas_contention_timeout_in_ms: 1000  
truncate_request_timeout_in_ms: 60000  
request_timeout_in_ms: 10000`

**Review by ligangty — COMMENTED** [review]
LGTM

**Pull request merged**
