### PR TITLE
Revert the write-consistency level to ALL

### PR DESCRIPTION
**Pull request by ruhan1**
Revert the write-consistency level to ALL since Indy always checks the existence right after writing. We have many ways to handle write-timeout but only this way to solve the r-right-after-w problem.

### CODE REVIEW

**Comment by sswguo** [comment]
LGTM, let's do more test.

**Review by ligangty — COMMENTED** [review]
LGTM

**Comment by ruhan1** [comment]
I hold this. Will close it if the other pr works.

**Comment by ruhan1** [comment]
Abandoned.

**Pull request closed without merging**
